# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on:
  # only run tests on push to main
  push:
    branches:
      - main
  # run tests for all pull requests
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Build CI workflow
      uses: adafruit/workflows-circuitpython-libs/build@main
